name: Build and Test

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
 macos:
   name: macOS ${{ matrix.configuration }}
   runs-on: macos-latest
   strategy:
    fail-fast: false
    matrix:
        configuration: [debug, release]
   steps:
   - uses: fwal/setup-swift@v1
   - uses: actions/checkout@v2
   - uses: maxim-lobanov/setup-xcode@v1.1
     with:
       xcode-version: latest
   - name: Check Xcode version
     run: xcodebuild -version
   - name: Check Swift version
     run: swift --version
   - name: Build
     run: swift build
   - name: Test
     run: swift test
   - name: Debug Build & Test
     if: matrix.configuration == 'debug'
     run: swift test -c debug --enable-code-coverage -Xswiftc -DCOVERAGE
     env:
       ENABLE_DEPLOYMENT_PROVIDER_TESTS: YES
   - name: Convert coverage report
     if: matrix.configuration == 'debug'
     run: xcrun llvm-cov export -format="lcov" .build/debug/ApodiniMigratorPackageTests.xctest/Contents/MacOS/ApodiniMigratorPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
   - name: Upload coverage to Codecov
     uses: codecov/codecov-action@v1
 
